### ISSUE TITLE
Finalize level 

### ISSUE THREAD

**Issue by ArinvonKrogh** [Avokadoen/shipwrecked#13]

**Comment by Avokadoen** [comment]
Instead of using edge collider, we should use polygon collider on a invisible sprite that represent the collider

**Comment by Avokadoen** [comment]
This can be close as soon as #49 is resolved

**Comment by Avokadoen** [comment]
Reopen as i forgot we need foreground elements in the scene

**Comment by Avokadoen** [comment]
Resolved in 8a42991e822ff8364b2f89b921a2603d3b7120ee
