### ISSUE TITLE
Soundeffects

### ISSUE THREAD

**Issue by AgonTann** [Avokadoen/shipwrecked#22]
Create soundeffects for the different objects

- [x] Music track 
  - [x] Main menu
  - [x] In ocean (high tide)
  - [x] In combat (low tide)
- [x] Swimming sound
- [x] Pick up
- [x] Dirt footsteps
- [x] Blaster shot
- [x] Applying damage to rat - rat squeak
- [x] Rat attacking
- [x] Rat death
- [x] Taking damage sound (player)
- [x] Rat running
- [x] Building building
- [x] Building destroyed
- [x] Dying (player)

**Comment by Avokadoen** [comment]
Reopen as assets are not pushed to master
