### ISSUE TITLE
Sound Clips

### ISSUE THREAD

**Issue by ArinvonKrogh** [Avokadoen/shipwrecked#44]
- [x] Gun blast
- [x] Build
- [x] Building destroyed
- [x] Player pick up resources 
- [x] Player take damage
- [x] Player death
- [x] Rat take damage
- [x] Rat death
- [x] Upgrade ship
- [x] Bullet hit
- [x] Footstep
- [x] Swim

**Comment by Avokadoen** [comment]
Gun blast:  260f58fa5f12f953d578b025c999f975562c923c
On the pistol prefab OARangedWeapon now has an event "onFire"

**Comment by Avokadoen** [comment]
Building built/destroyed: TODO
Prefab Barricade -> OABuildingArea
Prefab Spaceship -> OABuildingArea

**Comment by Avokadoen** [comment]
Damage & death
Prefab Player damage and death -> OAKillable
Prefab Rat damage and death -> OAKillable
