### ISSUE TITLE
Spaceship AI (Dialog system)

### ISSUE THREAD

**Issue by ArinvonKrogh** [Avokadoen/shipwrecked#58]
| Trigger | Message |
| ------------- | ------------- |
| On start (High tide) | Initial situation analysis: |
|   | Location: E4RTH00  |
|   | Spaceship status: 2 of 4 engines incapacitated. Repairs required.  |
|   | Spaceship status: Solar radiation shield at 46 % capacity. Repairs required.  |
|   | Spaceship status: Windshields broken. Repairs required.  |
|   | Scanning... |
|   | Scanning results: Materials required for repair most likely to be found below water surface |
|   | Scanning... |
|   | Scanning results: No hostile life forms found below water surface |
| On low tide | Warning: Water levels dropping due to gravitational pull from planets moon  |
| On rat attack | Warning: hostile terrestrial life form approaching. Self-defence systems incapacitated  |
|   | Suggestion: Protect spaceship (Please help) |
| After rat attack | More hostile terrestrial life forms nearby |
|  | Suggestion: Protect spaceship while water levels are low |
|  | Suggestion: Search for materials required for spaceship repair while water levels are high |

**Comment by ArinvonKrogh** [comment]
| Trigger | Message |
| ------------- | ------------- |
| Every low tide  | Water levels dropping  |
| Every low tide  | Hostile terrestrial life forms approaching  |
| When last rat killed  | All nearby hostile terrestrial life forms terminated  |

**Comment by Avokadoen** [comment]
This is currently functional as of f031336795d27a506e047596fc3bb278a4f69886
